In [ ]:

#pip install transformers torch

Requirement already satisfied: transformers in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (5.9.0)
Requirement already satisfied: torch in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (2.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from transformers) (1.17.0)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\appdata\roaming\python\python310\site-packages (from transformers) (26.2)
Requirement already satisfied: typer in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: numpy>=1.17 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2.2.6)
Requirement already satisfied: regex>=2025.10.22 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\asus\appdata\roaming\python\python310\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from torch) (65.5.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: filelock in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from torch) (3.29.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from torch) (2026.4.0)
Requirement already satisfied: click>=8.4.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python310\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: rich>=13.8.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: certifi in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: anyio in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: idna in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.16)
Requirement already satisfied: h11>=0.16 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\asus\appdata\roaming\python\python310\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\asus\appdata\roaming\python\python310\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from transformers import pipeline

In [2]:
df = pd.read_csv("sentiment analysis.csv")

df.head()

,Complaint ID,Category,Sub Category,Grievance Date,Ward Name,Grievance Status,Staff Remarks,Staff Name
0,20771690,Electrical,Street Light Not Working,2025-06-19 10:39:00.000000000,Jagajeevanram Nagar,Registered,1st Assignment Based on Ward Mapping,syed zameer/JE
1,20771689,Electrical,Street Light Not Working,2025-06-19 10:36:00.000000000,Kammanahalli,Registered,1st Assignment Based on Ward Mapping,Vinay Kumar/AE
2,20771688,Solid Waste (Garbage) Related,Garbage dump,2025-06-19 10:35:00.000000000,Banaswadi,Registered,1st Assignment Based on Ward Mapping,Marshal Ward No 27/Marshal
3,20771687,Electrical,Street Light Not Working,2025-06-19 10:34:00.000000000,Gandhi Nagar,Registered,1st Assignment Based on Ward Mapping,syed zameer/JE
4,20771686,Solid Waste (Garbage) Related,Garbage dump,2025-06-19 10:34:00.000000000,Kumaraswamy Layout,Registered,1st Assignment Based on Ward Mapping,Marshal Ward No 181/Marshal

In [9]:
df.shape

df.columns

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 126920 entries, 0 to 126973
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Complaint ID      126920 non-null  int64
 1   Category          126920 non-null  object
 2   Sub Category      126920 non-null  object
 3   Grievance Date    126920 non-null  object
 4   Ward Name         126920 non-null  object
 5   Grievance Status  126920 non-null  object
 6   Staff Remarks     126920 non-null  object
 7   Staff Name        126920 non-null  object
 8   clean_text        126920 non-null  object
dtypes: int64(1), object(8)
memory usage: 9.7+ MB

Complaint ID        0
Category            0
Sub Category        0
Grievance Date      0
Ward Name           0
Grievance Status    0
Staff Remarks       0
Staff Name          0
clean_text          0
dtype: int64

In [10]:
df.dropna(inplace=True)

df.drop_duplicates(inplace=True)

df.shape

(126920, 9)

In [11]:
import re

def clean_text(text):
    
    text = str(text).lower()
    
    text = re.sub(r'http\S+', '', text)
    
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()

In [12]:
df['clean_text'] = df['Sub Category'].apply(clean_text)

df[['Sub Category','clean_text']].head()

               Sub Category                clean_text
0  Street Light Not Working  street light not working
1  Street Light Not Working  street light not working
2              Garbage dump              garbage dump
3  Street Light Not Working  street light not working
4              Garbage dump              garbage dump

In [13]:
import nltk

nltk.download('punkt')

nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [14]:
import re

def clean_text(text):
    
    text = str(text).lower()
    
    text = re.sub(r'http\S+', '', text)
    
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()

df['clean_text'] = df['Sub Category'].apply(clean_text)

df[['Sub Category', 'clean_text']].head()

               Sub Category                clean_text
0  Street Light Not Working  street light not working
1  Street Light Not Working  street light not working
2              Garbage dump              garbage dump
3  Street Light Not Working  street light not working
4              Garbage dump              garbage dump

In [15]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    
    words = word_tokenize(text)
    
    filtered = [word for word in words if word not in stop_words]
    
    return " ".join(filtered)

df['clean_text'] = df['clean_text'].apply(remove_stopwords)

df[['Sub Category','clean_text']].head()

               Sub Category            clean_text
0  Street Light Not Working  street light working
1  Street Light Not Working  street light working
2              Garbage dump          garbage dump
3  Street Light Not Working  street light working
4              Garbage dump          garbage dump

In [16]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [17]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    
    words = text.split()
    
    words = [lemmatizer.lemmatize(word) for word in words]
    
    return " ".join(words)

df['clean_text'] = df['clean_text'].apply(lemmatize_text)

df[['Sub Category','clean_text']].head()

               Sub Category            clean_text
0  Street Light Not Working  street light working
1  Street Light Not Working  street light working
2              Garbage dump          garbage dump
3  Street Light Not Working  street light working
4              Garbage dump          garbage dump

In [18]:
df['clean_text'].head()

0    street light working
1    street light working
2            garbage dump
3    street light working
4            garbage dump
Name: clean_text, dtype: object

In [19]:
df.to_csv("cleaned_grievance_data.csv",index=False)

In [20]:
df.head()

,Complaint ID,Category,Sub Category,Grievance Date,Ward Name,Grievance Status,Staff Remarks,Staff Name,clean_text
0,20771690,Electrical,Street Light Not Working,2025-06-19 10:39:00.000000000,Jagajeevanram Nagar,Registered,1st Assignment Based on Ward Mapping,syed zameer/JE,street light working
1,20771689,Electrical,Street Light Not Working,2025-06-19 10:36:00.000000000,Kammanahalli,Registered,1st Assignment Based on Ward Mapping,Vinay Kumar/AE,street light working
2,20771688,Solid Waste (Garbage) Related,Garbage dump,2025-06-19 10:35:00.000000000,Banaswadi,Registered,1st Assignment Based on Ward Mapping,Marshal Ward No 27/Marshal,garbage dump
3,20771687,Electrical,Street Light Not Working,2025-06-19 10:34:00.000000000,Gandhi Nagar,Registered,1st Assignment Based on Ward Mapping,syed zameer/JE,street light working
4,20771686,Solid Waste (Garbage) Related,Garbage dump,2025-06-19 10:34:00.000000000,Kumaraswamy Layout,Registered,1st Assignment Based on Ward Mapping,Marshal Ward No 181/Marshal,garbage dump

In [21]:
classifier = pipeline("sentiment-analysis")

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ASUS\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [22]:
sample_text = "Garbage is overflowing near the road"

result = classifier(sample_text)

print(result)

[{'label': 'NEGATIVE', 'score': 0.999545156955719}]

In [23]:
df['bert_sentiment'] = df['clean_text'].apply(
    lambda x: classifier(str(x))[0]['label']
)
df[['clean_text','bert_sentiment']].head()

             clean_text bert_sentiment
0  street light working       POSITIVE
1  street light working       POSITIVE
2          garbage dump       NEGATIVE
3  street light working       POSITIVE
4          garbage dump       NEGATIVE

In [24]:
print(df.columns)

Index(['Complaint ID', 'Category', 'Sub Category', 'Grievance Date',
       'Ward Name', 'Grievance Status', 'Staff Remarks', 'Staff Name',
       'clean_text', 'bert_sentiment'],
      dtype='object')