In [1]:
#pip install transformers torch

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from transformers import pipeline

In [3]:
df = pd.read_csv("sentiment analysis.csv")

df.head()

,Complaint ID,Category,Sub Category,Grievance Date,Ward Name,Grievance Status,Staff Remarks,Staff Name
0,20771690,Electrical,Street Light Not Working,2025-06-19 10:39:00.000000000,Jagajeevanram Nagar,Registered,1st Assignment Based on Ward Mapping,syed zameer/JE
1,20771689,Electrical,Street Light Not Working,2025-06-19 10:36:00.000000000,Kammanahalli,Registered,1st Assignment Based on Ward Mapping,Vinay Kumar/AE
2,20771688,Solid Waste (Garbage) Related,Garbage dump,2025-06-19 10:35:00.000000000,Banaswadi,Registered,1st Assignment Based on Ward Mapping,Marshal Ward No 27/Marshal
3,20771687,Electrical,Street Light Not Working,2025-06-19 10:34:00.000000000,Gandhi Nagar,Registered,1st Assignment Based on Ward Mapping,syed zameer/JE
4,20771686,Solid Waste (Garbage) Related,Garbage dump,2025-06-19 10:34:00.000000000,Kumaraswamy Layout,Registered,1st Assignment Based on Ward Mapping,Marshal Ward No 181/Marshal

In [4]:
df.shape

df.columns

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126974 entries, 0 to 126973
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Complaint ID      126974 non-null  int64
 1   Category          126974 non-null  object
 2   Sub Category      126974 non-null  object
 3   Grievance Date    126974 non-null  object
 4   Ward Name         126974 non-null  object
 5   Grievance Status  126920 non-null  object
 6   Staff Remarks     126920 non-null  object
 7   Staff Name        126920 non-null  object
dtypes: int64(1), object(7)
memory usage: 7.8+ MB

Complaint ID         0
Category             0
Sub Category         0
Grievance Date       0
Ward Name            0
Grievance Status    54
Staff Remarks       54
Staff Name          54
dtype: int64

In [5]:
df.dropna(inplace=True)

df.drop_duplicates(inplace=True)

df.shape

(126920, 8)

In [6]:
import re

def clean_text(text):
    
    text = str(text).lower()
    
    text = re.sub(r'http\S+', '', text)
    
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()

In [7]:
df['clean_text'] = df['Sub Category'].apply(clean_text)

df[['Sub Category','clean_text']].head()

               Sub Category                clean_text
0  Street Light Not Working  street light not working
1  Street Light Not Working  street light not working
2              Garbage dump              garbage dump
3  Street Light Not Working  street light not working
4              Garbage dump              garbage dump

In [16]:
import nltk

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\sarov\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [17]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sarov\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sarov\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [18]:
import re

def clean_text(text):
    
    text = str(text).lower()
    
    text = re.sub(r'http\S+', '', text)
    
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()

df['clean_text'] = df['Sub Category'].apply(clean_text)

df[['Sub Category', 'clean_text']].head()

               Sub Category                clean_text
0  Street Light Not Working  street light not working
1  Street Light Not Working  street light not working
2              Garbage dump              garbage dump
3  Street Light Not Working  street light not working
4              Garbage dump              garbage dump

In [19]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sarov\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    
    words = word_tokenize(text)
    
    filtered = [word for word in words if word not in stop_words]
    
    return " ".join(filtered)

df['clean_text'] = df['clean_text'].apply(remove_stopwords)

df[['Sub Category','clean_text']].head()

               Sub Category            clean_text
0  Street Light Not Working  street light working
1  Street Light Not Working  street light working
2              Garbage dump          garbage dump
3  Street Light Not Working  street light working
4              Garbage dump          garbage dump

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sarov\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [21]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    
    words = text.split()
    
    words = [lemmatizer.lemmatize(word) for word in words]
    
    return " ".join(words)

df['clean_text'] = df['clean_text'].apply(lemmatize_text)

df[['Sub Category','clean_text']].head()

               Sub Category            clean_text
0  Street Light Not Working  street light working
1  Street Light Not Working  street light working
2              Garbage dump          garbage dump
3  Street Light Not Working  street light working
4              Garbage dump          garbage dump

In [22]:
df['clean_text'].head()

0    street light working
1    street light working
2            garbage dump
3    street light working
4            garbage dump
Name: clean_text, dtype: object